### ISSUE TITLE
What does inferred mean in combined.motif2factors?

### ISSUE THREAD

**Issue by roryk** [vanheeringen-lab/gimmemotifs#279]
`gimme motifs`finds a denovo motif, with this sequence logo:

![image](https://user-images.githubusercontent.com/414586/192544162-64adfe4c-a6c6-4456-ac20-ad74474b24f6.png)

And claims it is inferred that YY1 is a factor that will bind it, but YY1 has a very different looking binding motif. What does inferred mean? How should I interpret this? I searched through the manual but didn't find anything describing what inferred meant.

Thank you so much!

**Comment by simonvh** [comment]
Hi @roryk , inferred means that there is no direct evidence for that specific factor binding to a motif. For known motifs, this can be because the binding was inferred through DNA-binding domain similarity (CIS-BP), for instance.
For a *de novo* motifs, the binding TF is always "inferred" as we have no TF information :). This is based on motif similarity. If a *de novo* motif clusters together with other motifs, and these motifs have a TF assigned, then that TF is assigned to the *de novo* motif. If you take the reverse complement of this motif, you see that the CCAT core of the YY1 motif matches from position 2-5 (ATGG). Essentially, position 1-6 seems to match the YY1 motif: GCCATC / GATGGC.

**Comment by roryk** [comment]
Thank you so much, that is super helpful!
