### ISSUE TITLE
gimme index

### ISSUE THREAD

**Issue by yongjieliu** [vanheeringen-lab/gimmemotifs#75]
Hello:
 
I got an strange error after running `gimme index -h`

`usage: gimme [-h] <subcommand> [options]
gimme: error: invalid choice: 'index' (choose from 'motifs', 'match', 'maelstrom', 'roc', 'cluster', 'background', 'threshold', 'location', 'scan', 'diff', 'logo', 'prediction')`

And the manual said that I could create an index with `gimme index` command

**Comment by simonvh** [comment]
Sorry for not being more clear on this in the documentation. The `gimme index` documentation should be removed. GimmeMotifs now uses [genomepy](https://github.com/simonvh/genomepy) for genome management. In addition any FASTA file (with all chromosomes in one file) can now be used instead of a genome name.

>The way genomes are installed and used has been changed from 0.11.1 to 0.12.0. Basically, we have >switched to the faidx index used and supported by many other tools. This means that the old >(<=0.11.1) GimmeMotifs index cannot be used by GimmeMotifs 0.12.0 and higher. You can re-install >genomes using genomepy, which is now the preferred tool for genome management for GimmeMotifs. >However, because of this change you can now also directly supply a genome FASTA instead of a >genome name. Pre-indexing is not required anymore.
